name: Run Unit Tests

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup pnpm and Node.js
        uses: pnpm/setup@v2
        with:
          runtime: node@24
          cache: true
          require-lockfile: true

      - name: Run unit tests
        run: pnpm test:unit:run
